<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="camera">
    <!-- 
        camera_{x,y,z,mass} are physical properties of camera collision model
        lens_{r, h, mass} are physical properties of the camera lens
        hfov, fps, width, height, format, near, and far are simulation
    -->
    <xacro:macro name="camera"
        params="frame:=camera name:=camera camera_x:=0.047758 camera_y:=0.029 camera_z:=0.029 camera_mass:=0.03
                lens_r:=0.016 lens_h:=0.035 lens_mass:=0.05 
                hfov:=1.0471975512 fps:=23 width:=720 height:=540 format:=R8G8B8 near:=0.5 far:=300 connected_to:='' ns:='' rpy:='0 0 0' xyz:='0 0 0' ">

        <!-- Joint definition if connected_to is specified -->
        <xacro:unless value="${connected_to == ''}">
            <joint name="${ns}_camera_joint" type="fixed">
                <parent link="${connected_to}"/>
                <child link="${frame}"/>
                <origin xyz="${xyz}" rpy="${rpy}"/>
            </joint>
        </xacro:unless>

        <!-- Camera body link -->
        <link name="${frame}">
            <inertial>
                <mass value="${camera_mass}" />
                <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
            </inertial>
            <visual>
                <origin xyz="0 0 0.01425" rpy="0 0 0" />
                <geometry>
                    <mesh filename="package://flir_camera_description/meshes/flir_blackfly_s.stl"/>
                </geometry>
                <material name="dark_grey"><color rgba="0.2 0.2 0.2 1"/></material>
            </visual>
            <collision>
                <origin xyz="0.003 0 ${camera_z/2}" rpy="0 0 0" />
                <geometry>
                    <box size="${camera_x} ${camera_y} ${camera_z}" />
                </geometry>
            </collision>
        </link>

        <!-- Lens link -->
        <link name="${frame}_lens">
            <inertial>
                <mass value="${lens_mass}" />
                <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
            </inertial>
            <visual>
                <origin xyz="${lens_h/2} 0 0" rpy="0 1.5707 0" />
                <geometry>
                    <cylinder radius="${lens_r}" length="${lens_h}"/>
                </geometry>
                <material name="dark_grey"><color rgba="0.2 0.2 0.2 1"/></material>
            </visual>
            <collision>
                <origin xyz="${lens_h/2} 0 0" rpy="0 1.5707 0" />
                <geometry>
                    <cylinder radius="${lens_r}" length="${lens_h}"/>
                </geometry>
            </collision>
        </link>

        <!-- Optical frame (for Gazebo camera sensor) -->
        <link name="${frame}_optical" />

        <!-- Joints between camera, lens, and optical frame -->
        <joint name="${frame}_lens_joint" type="fixed">
            <origin xyz="0.02685 0 0.01425" rpy="0 0 0" />
            <parent link="${frame}" />
            <child link="${frame}_lens" />
        </joint>

        <joint name="${frame}_optical_joint" type="fixed">
            <origin xyz="${lens_h} 0 0" rpy="-1.570796 0 -1.570796" />
            <parent link="${frame}_lens" />
            <child link="${frame}_optical" />
        </joint>

        <!-- Gazebo camera sensor configuration -->
        <gazebo reference="${frame}_optical">
            <material>Gazebo/Grey</material>
            <sensor type="camera" name="${name}">
                <update_rate>${fps}</update_rate>
                <camera name="${name}">
                    <pose>0 0 0 0 -1.5707 1.5707</pose>
                    <horizontal_fov>${hfov}</horizontal_fov>
                    <image>
                        <width>${width}</width>
                        <height>${height}</height>
                        <format>${format}</format>
                    </image>
                    <clip>
                        <near>${near}</near>
                        <far>${far}</far>
                    </clip>
                    <noise>
                        <type>gaussian</type>
                        <mean>0.0</mean>
                        <stddev>0.007</stddev>
                    </noise>
                </camera>

                <plugin name="camera_controller" filename="libgazebo_ros_camera.so">
                    <alwaysOn>true</alwaysOn>
                    <updateRate>${fps}</updateRate>
                    <cameraName>${name}</cameraName>
                    <imageTopicName>image_raw</imageTopicName>
                    <cameraInfoTopicName>camera_info</cameraInfoTopicName>
                    <frameName>${frame}_optical</frameName>
                    <hackBaseline>0.07</hackBaseline>
                    <distortionK1>0.0</distortionK1>
                    <distortionK2>0.0</distortionK2>
                    <distortionK3>0.0</distortionK3>
                    <distortionT1>0.0</distortionT1>
                    <distortionT2>0.0</distortionT2>
                </plugin>
            </sensor>
        </gazebo>
    </xacro:macro>
</robot>
